name: An empty space
favicon: null
layout_spectrum: 0.75017
typography_spectrum: 0.24412
title: Peter Noble - agile storyteller
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-2502854-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#837d6c'
    - '#84a8e2'
    - '#514d3b'
    - '#22231c'
    - '#bfc17a'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
