name: An empty space
favicon: null
layout_spectrum: 0.5852979710325599
typography_spectrum: 0.5090862726792693
title: Peter Noble - agile storyteller
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-2502854-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.08753613359294832
  lightness: 0.9179283522535115
  saturation: 0.06271706381812692
  rhythmicContrast: 0.9673123594839126
purpose: []
